# Generated by Django 3.1.3 on 2020-12-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('course', models.TextField(max_length=100)),
                ('timendate', models.TextField(max_length=100)),
                ('extra', models.TextField(max_length=50)),
            ],
        ),
    ]
