# Generated by Django 3.1.3 on 2020-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='extra',
            field=models.IntegerField(max_length=10),
        ),
    ]
